apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp-deployment
  labels:
    app: chatapp
spec:
  selector:
    matchLabels:
      app: chatapp
  template:
    metadata:
      labels:
        app: chatapp
    spec:
      containers:
      - name: chatapp-container
        image: chat_app
        imagePullPolicy: Never # https://medium.com/swlh/how-to-run-locally-built-docker-images-in-kubernetes-b28fbc32cc1d
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
        ports:
        - containerPort: 8080

# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: inventory-deployment
#   labels:
#     app: inventory
# spec:
#   selector:
#     matchLabels:
#       app: inventory
#   template:
#     metadata:
#       labels:
#         app: inventory
#     spec:
#       containers:
#       - name: inventory-container
#         image: inventory:1.0-SNAPSHOT
#         ports:
#         - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: chatapp-service
spec:
  type: LoadBalancer
  selector:
    app: chatapp
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31000

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: inventory-service
# spec:
#   type: NodePort
#   selector:
#     app: inventory
#   ports:
#   - protocol: TCP
#     port: 9080
#     targetPort: 9080
#     nodePort: 32000